# Generated by Django 2.2.4 on 2020-08-30 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Day')),
            ],
        ),
        migrations.CreateModel(
            name='TravelLocationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('TravelLocation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.TravelLocation')),
            ],
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.AddField(
            model_name='day',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Travel'),
        ),
    ]
