# Generated by Django 2.2.4 on 2020-09-02 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200830_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='travellocation',
            name='travel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Travel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travel',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='travellocation',
            name='day',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
